const app=document.querySelector('#app');
const state={role:localStorage.getItem('bali.role')||'bartender',fio:localStorage.getItem('bali.fio')||'',gateway:localStorage.getItem('bali.gateway')||'',token:localStorage.getItem('bali.token')||'',content:null,quiz:null};
const roleName=r=>r==='bartender'?'БАРМЕН':'ОФИЦИАНТ';
const uid=()=>crypto.randomUUID();
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
async function loadContent(){if(state.content)return state.content;const [k,c]=await Promise.all([fetch('./content/knowledge.json').then(r=>r.json()),fetch('./content/cocktails-extra.json').then(r=>r.json()).catch(()=>({cocktails:[]}))]);state.content={...k,cocktails:[...(k.cocktails||[]),...(c.cocktails||[])]};return state.content}
async function api(path,opts={}){if(!state.gateway)throw new Error('Gateway не настроен');const headers={'Content-Type':'application/json',...(opts.headers||{})};if(state.token)headers.Authorization=`Bearer ${state.token}`;const r=await fetch(state.gateway.replace(/\/$/,'')+path,{...opts,headers});if(!r.ok)throw new Error((await r.json().catch(()=>({}))).error||`HTTP ${r.status}`);return r.json()}
async function register(){const fio=document.querySelector('#fio').value.trim();if(fio.split(/\s+/).length<2){msg('Введите ФИО полностью','error');return}state.fio=fio;localStorage.setItem('bali.fio',fio);localStorage.setItem('bali.role',state.role);const gateway=document.querySelector('#gateway')?.value.trim()||state.gateway;if(gateway){state.gateway=gateway;localStorage.setItem('bali.gateway',gateway);try{const d=await api('/api/register',{method:'POST',body:JSON.stringify({fio,role:state.role,deviceId:localStorage.getItem('bali.device')||(()=>{const x=uid();localStorage.setItem('bali.device',x);return x})()})});state.token=d.token;localStorage.setItem('bali.token',d.token)}catch(e){msg('Вход сохранён локально. Синхронизация: '+e.message,'warn')}}home()}
function shell(body,active='home'){app.innerHTML=`<div class="wrap"><div class="topline"><div><div class="brand">BALI</div><div class="sub">ACADEMY • ${roleName(state.role)}</div></div><button class="ghost" onclick="settings()">⚙︎</button></div>${body}</div><nav class="nav"><button class="${active==='home'?'active':''}" onclick="home()">Главная</button><button class="${active==='learn'?'active':''}" onclick="learn()">База</button><button class="${active==='quiz'?'active':''}" onclick="quizSetup()">Тест</button><button class="${active==='ai'?'active':''}" onclick="aiView()">AI</button></nav>`}
function onboarding(){app.innerHTML=`<div class="wrap"><div class="brand">BALI</div><div class="sub">ACADEMY • iPhone</div><h1>Обучение персонала</h1><p class="muted">Введите ФИО и выберите должность. На новом устройстве используйте те же ФИО и роль.</p><div class="card"><div class="field"><label>ФИО</label><input id="fio" autocomplete="name" value="${esc(state.fio)}" placeholder="Иванов Иван Иванович"></div><div class="field"><label>ДОЛЖНОСТЬ</label><div class="roles"><button id="rb" class="role ${state.role==='bartender'?'active':''}" onclick="pickRole('bartender')"><b>🍸 БАРМЕН</b><span>Продукт • техника • коктейли</span></button><button id="rw" class="role ${state.role==='waiter'?'active':''}" onclick="pickRole('waiter')"><b>🍽 ОФИЦИАНТ</b><span>Меню • сервис • продажи</span></button></div></div><div class="field"><label>GATEWAY URL <span class="muted">(для синхронизации)</span></label><input id="gateway" inputmode="url" value="${esc(state.gateway)}" placeholder="https://...vercel.app"></div><button class="primary" onclick="register()">ВОЙТИ В BALI ACADEMY</button><p id="message" class="warn"></p></div></div>`}
function pickRole(r){state.role=r;document.querySelector('#rb').classList.toggle('active',r==='bartender');document.querySelector('#rw').classList.toggle('active',r==='waiter')}
function msg(t,cls='warn'){const el=document.querySelector('#message');if(el){el.className=cls;el.textContent=t}}
function home(){if(!state.fio)return onboarding();shell(`<h1>${esc(state.fio)}</h1><p class="muted">${roleName(state.role)} • персональный профиль</p><div class="grid"><div class="tile" onclick="learn()"><b>${state.role==='bartender'?'Алкоголь и коктейли':'Меню и алкоголь'}</b><span>${state.role==='bartender'?'История, подача, стекло, матчасть':'Ассортимент, цены, сервис и рекомендации'}</span></div><div class="tile" onclick="quizSetup()"><b>Тестирование</b><span>10 / 20 / 30 / 50 / 100 случайных вопросов</span></div><div class="tile" onclick="sales()"><b>Психология продаж</b><span>Premium, upsell, работа с возражениями</span></div><div class="tile" onclick="aiView()"><b>AI‑тренер</b><span>Опечатки, русские/английские названия и обучение</span></div></div><div class="card"><span class="pill">GitHub storage</span><h2>Синхронизация</h2><p class="${state.gateway&&state.token?'muted':'warn'}">${state.gateway&&state.token?'Профиль подключён к gateway. Результаты тестов отправляются администратору.':'Сейчас локальный режим. В настройках укажите gateway URL, чтобы администратор видел результаты.'}</p></div>`,'home')}
async function learn(){const c=await loadContent();const lessons=(c.lessons||[]).filter(x=>!x.roles||x.roles.includes(state.role));const cocktails=(c.cocktails||[]).slice(0,20);shell(`<h1>База знаний</h1><div class="list">${lessons.map(x=>`<div class="item"><b>${esc(x.title)}</b><small>${esc(x.category)} • уровень ${x.level||1}</small><p>${esc(x.body)}</p></div>`).join('')}${state.role==='bartender'?cocktails.map(x=>`<div class="item"><b>${esc(x.name)}</b><small>${esc((x.aliases||[]).join(' • '))}</small><p>${esc(x.method||x.note||'')}</p></div>`).join(''):''}</div>`,'learn')}
async function sales(){const c=await loadContent();const l=(c.lessons||[]).filter(x=>/продаж/i.test(x.category||'')||/продаж/i.test(x.title||''));shell(`<h1>Продажи</h1><p class="muted">Техники продажи дорогого алкоголя в ночном клубе.</p><div class="list">${l.map(x=>`<div class="item"><b>${esc(x.title)}</b><p>${esc(x.body)}</p></div>`).join('')||'<div class="item">Материалы будут расширяться администратором.</div>'}</div>`,'learn')}
async function quizSetup(){const c=await loadContent();const q=(c.tests||[]).filter(x=>(!x.roles||x.roles.includes(state.role))&&x.type==='single');const cats=[...new Set(q.map(x=>x.category))];shell(`<h1>Тестирование</h1><div class="card"><div class="field"><label>КОЛИЧЕСТВО</label><select id="qc"><option>10</option><option>20</option><option>30</option><option>50</option><option>100</option></select></div><div class="field"><label>КАТЕГОРИЯ</label><select id="qcat"><option>Все</option>${cats.map(x=>`<option>${esc(x)}</option>`).join('')}</select></div><div class="field"><label>УРОВЕНЬ</label><select id="ql"><option value="0">Все уровни</option><option value="1">1</option><option value="2">2</option><option value="3">3</option><option value="4">4</option><option value="5">5</option></select></div><button class="primary" onclick="startQuiz()">НАЧАТЬ</button></div>`,'quiz')}
async function startQuiz(){const c=await loadContent();const count=+document.querySelector('#qc').value,cat=document.querySelector('#qcat').value,level=+document.querySelector('#ql').value;let pool=(c.tests||[]).filter(x=>x.type==='single'&&(!x.roles||x.roles.includes(state.role))&&(cat==='Все'||x.category===cat)&&(!level||x.level===level));pool=pool.sort(()=>Math.random()-.5).slice(0,Math.min(count,pool.length));state.quiz={items:pool,index:0,correct:0,errors:[],answers:[],startedAt:new Date().toISOString(),category:cat,level};renderQuestion()}
function renderQuestion(){const z=state.quiz;if(!z||z.index>=z.items.length)return finishQuiz();const q=z.items[z.index];const opts=q.options.map((v,i)=>({v,i})).sort(()=>Math.random()-.5);z.currentOrder=opts;shell(`<div class="topline"><span class="pill">${z.index+1} / ${z.items.length}</span><span class="muted">${esc(q.category)}</span></div><h1 class="question">${esc(q.question)}</h1><div id="options">${opts.map((o,n)=>`<button class="option" onclick="answer(${n})">${esc(o.v)}</button>`).join('')}</div><div id="feedback"></div>`,'quiz')}
function answer(n){const z=state.quiz,q=z.items[z.index],picked=z.currentOrder[n],ok=q.correct.includes(picked.i);if(ok)z.correct++;else z.errors.push({questionId:q.id,topic:q.category,selected:picked.v,correct:q.correct.map(i=>q.options[i]).join(', ')});z.answers.push({questionId:q.id,correct:ok});document.querySelectorAll('.option').forEach((b,i)=>{b.disabled=true;const original=z.currentOrder[i].i;if(q.correct.includes(original))b.classList.add('correct');else if(i===n&&!ok)b.classList.add('wrong')});document.querySelector('#feedback').innerHTML=`<div class="explain"><b>${ok?'Правильно':'Неправильно'}</b><br>${esc(q.explanation)}${!ok?`<br><br><b>Правильный ответ:</b> ${esc(q.correct.map(i=>q.options[i]).join(', '))}`:''}</div><button class="primary" style="margin-top:14px" onclick="nextQ()">ДАЛЬШЕ</button>`}
function nextQ(){state.quiz.index++;renderQuestion()}
async function finishQuiz(){const z=state.quiz,total=z.items.length,percent=total?Math.round(z.correct/total*100):0;const payload={id:uid(),mode:'mobileconfig-web',category:z.category,level:z.level,total,correct:z.correct,percent,errors:z.errors,answers:z.answers,startedAt:z.startedAt,completedAt:new Date().toISOString()};let sync='Локально сохранено';localStorage.setItem('bali.lastResult',JSON.stringify(payload));if(state.gateway&&state.token){try{await api('/api/result',{method:'POST',body:JSON.stringify(payload)});sync='Отправлено администратору'}catch(e){sync='Ошибка синхронизации: '+e.message}}shell(`<h1>Результат</h1><div class="card"><div class="score">${percent}%</div><p>${z.correct} из ${total} правильных</p><p class="muted">${esc(sync)}</p></div>${z.errors.length?`<h2>Ошибки</h2><div class="list">${z.errors.map(e=>`<div class="item"><b>${esc(e.topic)}</b><p>Ваш ответ: ${esc(e.selected)}<br><strong>Правильно: ${esc(e.correct)}</strong></p></div>`).join('')}</div>`:'<div class="card">Ошибок нет 🎉</div>'}<button class="primary" onclick="quizSetup()">ПЕРЕСДАТЬ</button>`,'quiz')}
function aiView(){shell(`<h1>AI‑тренер</h1><div class="card"><p class="muted">Можно писать по‑русски, по‑английски и с опечатками. Если найдено несколько похожих позиций, AI предложит выбор.</p><div class="field"><textarea id="aim" rows="5" placeholder="Например: как правильно подать макалан? Как приготовить лонг айленд?"></textarea></div><button class="primary" onclick="askAI()">СПРОСИТЬ</button><div id="aires"></div></div>`,'ai')}
async function askAI(){const t=document.querySelector('#aim').value.trim();if(!t)return;const box=document.querySelector('#aires');if(!(state.gateway&&state.token)){const c=await loadContent();const norm=s=>s.toLowerCase().replace(/[^a-zа-я0-9]/gi,'');const q=norm(t),all=[...(c.cocktails||[]),...(c.products||[])];const hits=all.filter(x=>[x.name,...(x.aliases||[])].some(n=>{const a=norm(n);return a&&q.includes(a.slice(0,Math.max(4,Math.min(a.length,8))))})).slice(0,5);box.innerHTML=`<div class="explain">Gateway не подключён. Локальный поиск:${hits.length?'<br>'+hits.map(x=>'• '+esc(x.name)).join('<br>'):' совпадений нет.'}</div>`;return}box.innerHTML='<p class="muted">Думаю…</p>';try{const d=await api('/api/ai',{method:'POST',body:JSON.stringify({message:t,mode:'trainer'})});box.innerHTML=`<div class="explain">${esc(d.text||d.message||'')}</div>${(d.options||[]).map(x=>`<div class="item">${esc(x.name)}</div>`).join('')}`}catch(e){box.innerHTML=`<p class="error">${esc(e.message)}</p>`}}
function settings(){shell(`<h1>Настройки</h1><div class="card"><div class="field"><label>GATEWAY URL</label><input id="sg" value="${esc(state.gateway)}" placeholder="https://...vercel.app"></div><button class="primary" onclick="saveGateway()">СОХРАНИТЬ И ПЕРЕПОДКЛЮЧИТЬ</button></div><div class="card"><b>${esc(state.fio)}</b><p class="muted">${roleName(state.role)}</p><button class="ghost" onclick="logout()">Сменить сотрудника</button></div>`,'home')}
async function saveGateway(){state.gateway=document.querySelector('#sg').value.trim().replace(/\/$/,'');localStorage.setItem('bali.gateway',state.gateway);state.token='';localStorage.removeItem('bali.token');onboarding()}
function logout(){state.fio='';state.token='';localStorage.removeItem('bali.fio');localStorage.removeItem('bali.token');onboarding()}
window.addEventListener('load',()=>state.fio?home():onboarding());
